version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - bodyclose
    - godot
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unused
    - whitespace

formatters:
  enable:
    - gofmt
    - goimports
