project_name: dbui
before:
  hooks:
    - go mod tidy
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    goarm:
      - "6"
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: dbui
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
release:
  github:
    owner: KenanBek
    name: dbui
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## Features

    List of newly introduced features:

    - Item 1
    - Item 2

    ## Bug fixes

    List of fixed issues:

    - Item 1
    - Item 2

    ## Code changes

    - Item 1
    - Item 2
  footer: |
    ## Thanks!

    Read more on our documentation page: https://kenanbek.gitbook.io/dbui/
brews:
  - tap:
      owner: KenanBek
      name: dbui
    name: dbui
    description: "Interactive terminal user interface and CLI for database connections. MySQL, PostgreSQL. More to come."
    homepage: "https://github.com/kenanbek/dbui"
    license: "Apache 2.0"
    folder: Formula
    commit_author:
      name: KenanBek
      email: mail@kenanbek.me
    install: bin.install "dbui"
    test: |
      system "#{bin/dbui}"
nfpms:
  - maintainer: KenanBek
    description: "Interactive terminal user interface and CLI for database connections. MySQL, PostgreSQL. More to come."
    homepage: "https://github.com/kenanbek/dbui"
    license: "Apache 2.0"
    formats:
      - deb
      - rpm
    replacements:
      darwin: Darwin
